### ISSUE TITLE
two <mask> raise IndexError

### ISSUE THREAD

**Issue by W-lw** [thunlp/OpenPrompt#13]
when I set two <mask> in the ManualTemplate :
```
promptTemplate = ManualTemplate(
    text = ["<text_a>", "was", "<mask>", 'and', '<mask>'],
    tokenizer = bertTokenizer,
)
```

it will raise:  
  "openprompt/prompts/manual_verbalizer.py", line 119, in project
    label_words_logits = logits[:, self.label_words_ids]
`IndexError: index 2204 is out of bounds for dimension 0 with size 2`

The whole code was copy from [link](https://thunlp.github.io/OpenPrompt/notes/examples.html#introduction-with-an-example)

**Comment by ningding97** [comment]
> when I set two in the ManualTemplate :
> 
> ```
> promptTemplate = ManualTemplate(
>     text = ["<text_a>", "was", "<mask>", 'and', '<mask>'],
>     tokenizer = bertTokenizer,
> )
> ```
> 
> it will raise: "openprompt/prompts/manual_verbalizer.py", line 119, in project label_words_logits = logits[:, self.label_words_ids] `IndexError: index 2204 is out of bounds for dimension 0 with size 2`
> 
> The whole code was copy from [link](https://thunlp.github.io/OpenPrompt/notes/examples.html#introduction-with-an-example)

In prompt-learning, a ''mask'' corresponds to a supervision signal, since normally there is only one label for an example, so you should only place one ''mask'' in the basic Template and Verbalizer classes. If you plan to predice multiple ''masks'', please refer to PTRTemplate and PTRVerbalizer. (We will consider to support multiple-mask in the base classes but with a warning)
