### ISSUE TITLE
Why does loss multiply by 1024 in the file (5.1_BMInf_CPM.py)?

### ISSUE THREAD

**Issue by ben-bo-er-ba** [thunlp/OpenPrompt#150]
Why does loss multiply by 1024 in the file (5.1_BMInf_CPM.py)?

**Comment by Achazwl** [comment]
Since model quantization is used, the range of the weight that can be expressed in PLM is not as large as fp32. So if we backward normally, the model may suffer from underflow, i.e., the gradient becomes too small to be expressed and go to zero, and keep being zero till the input template. Scaling the loss, so that the gradients are scaled too, can address this issue. Note that the learning rate of the input template is scaled down by a factor of 1024 too.

**Comment by Achazwl** [comment]
> Thanks for your reply. Is this data set(ChnSentiCorp) not integrated into this repository, Or download the original data set myself for processing?

you can download it yourself.

> When cpm2 is used for prompt tuning, is the input and output of PLM model in the following format?

yes

> and the maximum length of label mapping words is 5

see also #79, we would avoid label words that have a length more than one in Chinese. We would rather use label words that are existed in the vocabulary.
