### ISSUE TITLE
how to use bart on openprompt？ 

### ISSUE THREAD

**Issue by OTfish** [thunlp/OpenPrompt#37]
I'd like to use prefix tuning template and BARTmodel (As its paper does) , but found this template only supports T5 and GPT2. How to use BART in this work? And I found that the attention module of the transformer BART has been modified in original paper. If I want to use BART here, do I also need to modify it?

**Comment by ShengdingHu** [comment]
You may not need to modify the transformer's BART code. Just look at what we have done for T5, we wrap the original forward function of each transformer layer with a new forward function which passes `past_key_values` to the original transformer forward function. What need to be done to BART will be similar (I think). However, since we haven't support bart model yet, this functionality may be postponed to one or two weeks later (After the ACL :)

**Comment by ShengdingHu** [comment]
PRs are welcomed!

**Comment by BrettFyt** [comment]
> PRs are welcomed!

Hello author，have you ever used gpt2 for prompt test？If I want to output mask after the input without textual content，it will show "IndexError:index is out of bounds for dimension with size 0". Did I write something wrong？
For example：
`promptTemplate = ManualTemplate(
            text = '{"placeholder":"text_a"} {"mask"}' ,
            tokenizer = tokenizer
        )`
        `promptVerbalizer = ManualVerbalizer(
            classes = classes,
            label_words = {
                "1": ["one"],
                "2": ["two"],
                "3": ["three"]
            },
            tokenizer = tokenizer
        )`
