### ISSUE TITLE
naive finetune classication code  not found 

### ISSUE THREAD

**Issue by TheMrYang** [thunlp/OpenPrompt#38]

**Comment by ShengdingHu** [comment]
This is a good issue. Since it's a prompt learning package and naive finetuning doesn't belong to prompt-learning paradigm, so it may be a bit weird to add it to our package. However, most researches still have to compare with naive finetune, we are considering adding it to our framework in someway, may be with an empty template and a classification head `verbalizer`, but we are not so sure currently. You can implement and contribute by yourself currently!

**Comment by ningding97** [comment]
Why don't we take a poll? 😄
Should we add fine-tuning in OpenPrompt?

[![](https://api.gh-polls.com/poll/01FKZMFS189G0PBVQ69J3QCG0J/Yes)](https://api.gh-polls.com/poll/01FKZMFS189G0PBVQ69J3QCG0J/Yes/vote)
[![](https://api.gh-polls.com/poll/01FKZMFS189G0PBVQ69J3QCG0J/No)](https://api.gh-polls.com/poll/01FKZMFS189G0PBVQ69J3QCG0J/No/vote)

**Comment by huhk-sysu** [comment]
Hi, I'm new to prompt-learning and I find papers usually use it in a few-shot setting.
I wonder how does prompt-learning behave in a full dataset setting, does it still compettive to the naive finetuning, or just in some simple task like classification?

**Comment by ningding97** [comment]
> Hi, I'm new to prompt-learning and I find papers usually use it in a few-shot setting. I wonder how does prompt-learning behave in a full dataset setting, does it still compettive to the naive finetuning, or just in some simple task like classification?

To the best of  our knowledge, in the full-data setting, the prompt-learning paradigm will at least yield comparable results to fine-tuning.
