### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'tokenizer_wrapper_class'

### ISSUE THREAD

**Issue by dongxiaohuang** [thunlp/OpenPrompt#41]
When going through the [tutorial](https://thunlp.github.io/OpenPrompt/notes/examples.html)

In step 6, raised the errors below:

>>> data_loader = PromptDataLoader(
...     dataset = dataset,
...     tokenizer = bertTokenizer,
...     template = promptTemplate,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'tokenizer_wrapper_class'

**Comment by Doragd** [comment]
Hi, the documentation seems to be out-of-date. You can follow the tutorial via https://github.com/thunlp/OpenPrompt/tree/main/tutorial
or you should wrap the tokenizer before passed to the dataloader, e.g.
```
wrapped_t5tokenizer = WrapperClass(max_seq_length=128, decoder_max_length=3, tokenizer=tokenizer,truncate_method="head")
```

**Comment by ShengdingHu** [comment]
@Doragd  is correct. The reason is that we plan to not assume that we can infer tokenizer WrapperClass from tokenizer, since we are going to support T5-LM adaption version, where a t5tokenizer can be wrapped into different WrapperClasses. Therefore you should load the wrapperclass by yourself and pass it into the PromptDataloader.   We will update the document soon.

**Comment by Doragd** [comment]
@ShengdingHu  Do you mean that you are going to support LM-adapted T5 v1.1 checkpoints for prompt tuning? 
It is so exciting for me !

**Comment by ShengdingHu** [comment]
@Doragd Yes, of-course.
