### ISSUE TITLE
Recommended mix template for text classification task

### ISSUE THREAD

**Issue by gaoisbest** [thunlp/OpenPrompt#58]
[1.1_mixed_template.py Line 29](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/1.1_mixed_template.py#L29) gives an example usage of `MixedTemplate` for maybe question answering task, is there any recommended mix template for text classification task? 
For example is the following sentiment classification task code right ?

```
prompt_verbalizer = ManualVerbalizer(
    classes=classes,
    label_words={
        "negative": ["不"],
        "positive": ["很"],
    },
    tokenizer=tokenizer,
)

prompt_template = MixedTemplate(
    model=plm,
    tokenizer=tokenizer,
    text='{"soft"} {"soft"} {"soft"} {"placeholder":"text_a"} {"mask"}满意。'
)
```

**Comment by ningding97** [comment]
> [1.1_mixed_template.py Line 29](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/1.1_mixed_template.py#L29) gives an example usage of `MixedTemplate` for maybe question answering task, is there any recommended mix template for text classification task? For example is the following sentiment classification task code right ?
> 
> ```
> prompt_verbalizer = ManualVerbalizer(
>     classes=classes,
>     label_words={
>         "negative": ["不"],
>         "positive": ["很"],
>     },
>     tokenizer=tokenizer,
> )
> 
> prompt_template = MixedTemplate(
>     model=plm,
>     tokenizer=tokenizer,
>     text='{"soft"} {"soft"} {"soft"} {"placeholder":"text_a"} {"mask"}满意。'
> )
> ```

For English, there are many previous studies that try to construct textual templates. Since MixedTemplate is originated in OpenPrompt and there is still plenty of room for exploration. For example, we find that soft tokens + "The answer is: " is effective for BoolQ. We haven't conducted enough experiments on Chinese and we encourage you to explore and share your templates!

Spoiler alert: We are building a *Prompt Center* where users could download and upload trained prompts.
