### ISSUE TITLE
how to modify the batch size

### ISSUE THREAD

**Issue by One-punch24** [thunlp/OpenPrompt#68]
At first, thank you for your clean and beautiful code. 
I have a small question about the code.
In the prefixtuning template(tutorial 2.2), it seems that the code batchsize is fixed to  1, right?

**Comment by ShengdingHu** [comment]
If you use GPT-2 as the backbone and are in the generation process (not the training process), the answer is yes. Since it's very messy to use gpt-2 for batch generation if the sentences are of different lengths. Usually use the ``left padding`` trick or extract the last non-padding position's output (see [discussion](https://github.com/huggingface/transformers/issues/3021#issuecomment-591236688).  Here we did not implement it.

**Comment by One-punch24** [comment]
Thanks 👍 :), that seems useful
